# Configuration file for running a simulation

# SIMULATION PARAMETERS
mech_mesh = "mesh_mech_3.0" # mechanics mesh filepath without extension
outdir = "test_config_2ms_N10_try_to_break" # Output directory
sim_dur = 1 # Duration of simulation. Integer
dt = 0.05 # Timestep for ep solve
N = 10 # Solve mechanics step every nth ep solve

out_ep = ["cai", "v"]  # ep state parameters to output for all nodes, separated by comma, non-capitalised
out_mech = ["Ta", "lambda"]

out_ep_point.variables = ["cai", "v"] # ep state parameters to output at a given coordinate
out_ep_point.cai = [0, 0, 0] # coordinate for outputing ep parameter. currently a single point
out_ep_point.v = [0, 0, 0]

out_mech_point.variables = ["Ta"] # TODO: endure that it is a list
out_mech_point.Ta = [0, 0, 0]

# MODEL PARAMETERS
modelfile = "ORdmm_Land.ode"

# Tissue conductivity values. Currently only a single region, from p.4339 of Niederer benchmark
sigma_il = 0.17  # mS / mm
sigma_it = 0.019  # mS / mm
sigma_el = 0.62  # mS / mm
sigma_et = 0.24  # mS / mm

# Material parameters
# TODO: make material parameters more generic
mech_a=2.28
mech_a_f=1.686
mech_b=9.726
mech_b_f=15.779
mech_a_s=0.0
mech_b_s=0.0
mech_a_fs=0.0
mech_b_fs=0.0

# STIMULUS PARAMETERS
stim.start = 0.0
stim.amplitude = 50000.0 # mu A/cm^3
stim.duration = 2 # ms  
stim.xlim = [0.0, 1.5]  #1, 4    # Currently: Must both be floats or both integers
stim.ylim = [0.0, 1.5]  #0.5, 3
stim.zlim = [0.0, 1.5]  #0, 1

# BOUNDARY CONDITIONS
#bcs = 4 # TODO: Add  neuman and function as bcs
bcs.numbers = 3
bcs.markerfile = "mesh_mech_3dx_20Lx_7Ly_3Lz_surface_ffun"

# Mesh markers used for assigning bcs
bcs.0.marker = 1
bcs.0.type = "Dirichlet"
bcs.0.variable = "u_x"
bcs.0.func = 0

bcs.1.marker = 1 #3 # if same marker for ux,uy,uz, (e.g. marker = 1), then fixes the entire plane (plane with marker == 1)
bcs.1.type = "Dirichlet"
bcs.1.variable = "u_y"
bcs.1.func = 0

bcs.2.marker = 1 #5
bcs.2.type = "Dirichlet"
bcs.2.variable = "u_z"
bcs.2.func = 0

#bcs.3.marker = 2
#bcs.3.type = "Neumann"
#bcs.3.variable = None # Temporary. TODO: update to use this or remove
#bcs.3.func = a*t # Value can be a function of t
#bcs.3.func_params = a
#bcs.3.func_params.a = -2

