name: Test package

on:
  pull_request:
  push:
    branches: [main]


jobs:

  test-code:
    # This code depends on the result of check-code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2024-02-19


    steps:
      - uses: actions/checkout@v4

      - name: Install package
        run: python3 -m pip install -e .[test]

      - name: Run tests
        run: python3 -m pytest --cov=simcardems2 --cov-report=html --cov-report=term-missing -v

      - name: Upload HTML report.
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
